services:
  app:
    build: .
    ports:
      - target: 8000
        published: 8000
        mode: host
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    profiles:
      - dev
      - prod
    command: >
              uvicorn src.dual_choice.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - dual-choice-network


  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - db-data:/var/lib/postgresql/data
    # do not publish in production
    ports:
      - target: 5432
        published: 5432
        mode: host
    networks:
      - dual-choice-network

  redis:
    image: redis
    # do not publish it production
    ports:
      - target: 6379
        published: 6379
        mode: host
    volumes:
      - redis-data:/data
    networks:
      - dual-choice-network

  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        mode: host
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    profiles:
      - prod
    networks:
      - dual-choice-network

volumes:
  db-data:
  redis-data:

networks:
  dual-choice-network: