services:
  app:
    build: .
    ports:
    # should I leave this port exposed in production?
      - target: 8001
        published: 8001
        mode: host
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./results:/app/results
    profiles:
      - dev
      - prod
    command: >
      uvicorn src.dual_choice.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - dual-choice-network


  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dual-choice-network

  redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - dual-choice-network

  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        mode: host
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    profiles:
      - prod
    networks:
      - dual-choice-network

volumes:
  db-data:
  redis-data:

networks:
  dual-choice-network: