name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: extractions/setup-just@v1

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system -r requirements-dev.lock

      - name: Run unit tests
        run: just test

      - name: Run integration tests
        run: just test-db-redis
