name: Build and Push Docker Compose Images

on:
  push:
    branches:
      - change_to_main_when_ready

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker Compose images
      run: |
        docker-compose -f path/to/docker-compose.yml build
        docker-compose -f path/to/docker-compose.yml push